import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const interRegular = Inter({
  weight: "400",
  variable: "--font-inter-regular",
  subsets: ["latin"],
});

const interSemiBold = Inter({
  weight: "600",
  variable: "--font-inter-semibold",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vrit Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interRegular.variable} ${interSemiBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
